CREATE TABLE IF NOT EXISTS `RC_CONFIGURATION_DIFINITION`
(
   `NAME`                 VARCHAR(100) NOT NULL,
   `DESCP`                VARCHAR(50),
   PRIMARY KEY (`NAME`)
);
CREATE TABLE IF NOT EXISTS `RC_CONFIGURATION_VALUE`
(
   `CONFIG_NAME`          VARCHAR(100),
   `NAME`                 VARCHAR(50),
   `DESCP`                VARCHAR(50),
   VALUE                VARCHAR(300),
   PRIMARY KEY (`CONFIG_NAME`, `NAME`)
);
ALTER TABLE `RC_CONFIGURATION_VALUE` ADD CONSTRAINT FK_REFERENCE_CONFIG_NAME FOREIGN KEY (`CONFIG_NAME`)
      REFERENCES `RC_CONFIGURATION_DIFINITION` (`NAME`) ON DELETE RESTRICT ON UPDATE RESTRICT;
